// <auto-generated/>
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Net.Http;
global using global::System.Threading;
global using global::System.Threading.Tasks;

namespace taxi // Note: actual namespace depends on the project name.
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Taxi taxi = new Taxi();

            taxi.Name = "Ucok";
            taxi.Duty = true;
            taxi.Passanger = 10;

            taxi.TaxiInfo();
            taxi.PicUpPassanger();
            taxi.PicDownPassanger();

            Console.ReadKey();
        }

        public class Taxi
        {
            public string Name { get; set; }
            public bool Duty { get; set; }
            public int Passanger { get; set; }

            public void TaxiInfo()
            {
                Console.WriteLine("Driver: {0}", Name);
                Console.WriteLine("Duty: {0}", Duty);
                Console.WriteLine("Passanger: {0}", Passanger);
            }

            public void PicUpPassanger()
            {
                Console.WriteLine("{0} Sedang menjemput Penumpang", Name);
            }
            public void PicDownPassanger()
            {
                Console.WriteLine("{0} Sedang mengantar Penumpang", Name);
            }
        }
    }


}